spring:
  profiles:
    active: local
    group:
      local: site-local, db-local
      dev: site-dev
    include:
      - db
      - my-service
      - site
  banner:
    image:
      bitdepth: 8
      width: 100
      height: 15
